package net.H511F1R5.cooldownstairsmod.item.custom;

import net.H511F1R5.cooldownstairsmod.sounds.coolDownstairsSoundEvents;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.gameevent.GameEvent;

public class dummyFaceItem extends Item {
    private Level level;
    private Player player;
    private InteractionHand hand;
    private boolean rightclicked;

    public dummyFaceItem(Properties pProperties) {
        super(pProperties);     // Remember, this stuff gets autogenerated!\
    }

    public InteractionResultHolder<ItemStack> use(Level level, Player player, InteractionHand hand) {
        this.level = level;
        this.player = player;
        this.hand = hand;
        ItemStack itemStack = player.getItemInHand(hand);
        player.gameEvent(GameEvent.ITEM_INTERACT_START);
        player.playSound(coolDownstairsSoundEvents.DUMMY_FACE_USE.get(),1f, 1f);
        if (!level.isClientSide) {
            level.playSound(
                    player,
                    player.getX(), player.getY(), player.getZ(),
                    coolDownstairsSoundEvents.DUMMY_FACE_USE.get(),
                    SoundSource.PLAYERS,
                    5.0F,
                    1.0F
            );
        }
        player.getCooldowns().addCooldown(this, 20);
        player.sendSystemMessage(Component.literal("PINGAS @" + player.getX() + player.getY() + player.getZ()));
        return InteractionResultHolder.sidedSuccess(itemStack, level.isClientSide());
    }

}
