package net.H511F1R5.cooldownstairsmod.item.custom;

import net.H511F1R5.cooldownstairsmod.sounds.cooldownstairsSoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.context.UseOnContext;
import net.minecraft.world.level.Level;
import net.minecraftforge.client.event.sound.SoundEvent;
import org.jetbrains.annotations.NotNull;

public class dummyFaceItem extends Item {
    private Player user;
    private Level level;
    private Player player;
    private InteractionHand hand;

    public dummyFaceItem(Properties pProperties) {
        super(pProperties);     // Remember, this stuff gets autogenerated!\
    }

    @Override
    public InteractionResultHolder<ItemStack> use(Level level, Player player, InteractionHand hand) {
        if (!level.isClientSide()) {
            player.getCooldowns().addCooldown(this, 20);
            level.playSound(
                    null,
                    player.getX(), player.getY(), player.getZ(),
                    cooldownstairsSoundEvents.DUMMY_FACE_USE.get(),
                    SoundSource.BLOCKS,
                    1.0F,
                    1.0F
            );
        }

        return InteractionResultHolder.sidedSuccess(player.getItemInHand(hand), level.isClientSide());
    }
}
