package net.H511F1R5.cooldownstairsmod.item.custom;

import net.H511F1R5.cooldownstairsmod.sounds.cooldownstairsSoundEvents;
import net.minecraft.network.chat.Component;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.context.UseOnContext;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.state.BlockState;
import org.jetbrains.annotations.NotNull;

public class dummyFaceItem extends Item {
    private Level level;
    private Player player;
    private InteractionHand hand;
    private boolean rightclicked;

    public dummyFaceItem(Properties pProperties) {
        super(pProperties);     // Remember, this stuff gets autogenerated!\
    }

    @Override
    public @NotNull InteractionResultHolder<ItemStack> use(Level pLevel, Player player, InteractionHand hand) {
        this.level = pLevel;
        this.player = player;
        this.hand = hand;
        ItemStack itemStack = player.getItemInHand(hand);
        if (!level.isClientSide) {
            player.getCooldowns().addCooldown(this, 20);
            level.playSound(
                    null,
                    player.blockPosition(),
                    cooldownstairsSoundEvents.DUMMY_FACE_USE.get(),
                    SoundSource.MASTER,
                    5.0F,
                    1.0F
            );
            player.sendSystemMessage(Component.literal("PINGAS @" + player.getX() + player.getY() + player.getZ()));
        } else {
            player.sendSystemMessage(Component.literal("PINGAS FAILED!"));
        }
        return InteractionResultHolder.sidedSuccess(itemStack, level.isClientSide());
    }

    public InteractionResult useOn(BlockState state, Player player, Level level) {
        if (!level.isClientSide) {
            player.getCooldowns().addCooldown(this, 20);
            level.playSound(
                    null,
                    player.blockPosition(),
                    cooldownstairsSoundEvents.DUMMY_FACE_USE.get(),
                    SoundSource.MASTER,
                    5.0F,
                    1.0F
            );
            player.sendSystemMessage(Component.literal("PINGAS @" + player.getX() + player.getY() + player.getZ()));
        } else {
            player.sendSystemMessage(Component.literal("PINGAS FAILED!"));
        }
        return InteractionResult.SUCCESS;
    }

}
